version: '3'

services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    command: python manage.py runserver --nostatic 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    depends_on:
      - db