# Generated by Django 2.2.10 on 2020-03-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='related_users',
            new_name='rated_users',
        ),
    ]
