# Generated by Django 2.2.10 on 2020-06-30 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200301_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='posts/post_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rated_users',
            field=models.ManyToManyField(blank=True, related_name='ratings', to='users.MyUser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rubric',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Rubric'),
        ),
    ]
