# Generated by Django 2.2.10 on 2020-02-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentphoto',
            name='picture',
            field=models.ImageField(upload_to='users/comments/comments_photo'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(null=True, upload_to='users/avatars'),
        ),
    ]
