# Generated by Django 2.2.10 on 2020-03-01 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0002_auto_20200229_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='bookmarks',
            field=models.ManyToManyField(to='posts.Post'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='subscribed_rubrics',
            field=models.ManyToManyField(to='posts.Rubric'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='subscribed_users',
            field=models.ManyToManyField(related_name='_myuser_subscribed_users_+', to='users.MyUser'),
        ),
    ]
