# Generated by Django 2.2.10 on 2020-03-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200301_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentrate',
            old_name='comments',
            new_name='comment',
        ),
    ]
