# Generated by Django 2.2.10 on 2020-03-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200301_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rated_users',
            field=models.ManyToManyField(blank=True, related_name='rated_comments', through='users.CommentRate', to='users.MyUser'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='subscribed_rubrics',
            field=models.ManyToManyField(blank=True, to='posts.Rubric'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='subscribed_users',
            field=models.ManyToManyField(blank=True, related_name='_myuser_subscribed_users_+', to='users.MyUser'),
        ),
    ]
