# Generated by Django 2.2.10 on 2020-03-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200313_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentphoto',
            name='comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.Comment'),
        ),
    ]
