# Generated by Django 2.2.10 on 2020-03-13 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200313_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrate',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.MyUser'),
        ),
        migrations.AlterField(
            model_name='commentrate',
            name='comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.Comment'),
        ),
    ]
