# Generated by Django 2.2.10 on 2020-03-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200313_1612'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentrate',
            unique_together={('author', 'comment')},
        ),
    ]
