# Generated by Django 2.2.10 on 2020-03-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200318_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentphoto',
            name='picture',
            field=models.ImageField(upload_to='users/comments/photos'),
        ),
    ]
