# Generated by Django 2.2.10 on 2020-03-19 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200301_1315'),
        ('users', '0014_auto_20200319_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='myuser',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, through='users.Bookmark', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='my_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MyUser'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
